# Generated by Django 4.1.3 on 2023-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sukanta_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('PhoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('psw', models.IntegerField()),
                ('pswrepeat', models.IntegerField()),
            ],
            options={
                'db_table': 'sukanta_user',
            },
        ),
    ]
