# Generated by Django 4.1.3 on 2023-04-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sukanta_user',
            old_name='UserName',
            new_name='Username',
        ),
        migrations.AlterField(
            model_name='sukanta_user',
            name='PhoneNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sukanta_user',
            name='psw',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sukanta_user',
            name='pswrepeat',
            field=models.CharField(max_length=200),
        ),
    ]
